title: Hello, world!
description: A stream of random bytes
author: Ponnuvel Palaniyappan
github: https://github.com/pponnuvel
about: I am a systems programmer (Linux), based in the UK.
disqus_shortname: A stream of random bytes
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/pponnuvel"
    - icon: fa-linkedin
      link: "https://linkedin.com/in/pponnuvel"
    - icon: fa-stack-exchange
      link: "https://stackoverflow.com/users/1275169"
    - icon: fa-github
      link: "https://github.com/pponnuvel"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    # - text: My Projects
    #  url: /projects/
    # - text: XML Feed
    #  url: /feed.xml

url: "https://pponnuvel.github.io"
baseurl: https://pponnuvel.com
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
